export enum AuthActionType {
    AUTH_SIGN_IN_REQUEST = 'AUTH_SIGN_IN_REQUEST',
    AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS',
    AUTH_SIGN_IN_FAIL = 'AUTH_SIGN_IN_FAIL',

    AUTH_SIGN_UP_REQUEST = 'AUTH_SIGN_UP_REQUEST',
    AUTH_SIGN_UP_SUCCESS = 'AUTH_SIGN_UP_SUCCESS',
    AUTH_SIGN_UP_FAIL = 'AUTH_SIGN_UP_FAIL',

    AUTH_LOGOUT = 'AUTH_LOGOUT',
}
