export enum FeatureActionType {
    GET_ALL_FEATURES_REQUEST = 'GET_ALL_FEATURES_REQUEST',
    GET_ALL_FEATURES_SUCCESS = 'GET_ALL_FEATURES_SUCCESS',
    GET_ALL_FEATURES_FAIL = 'GET_ALL_FEATURES_FAIL',
}
