export enum GameActionType {
    FIND_GAMES_REQUEST = 'FIND_GAMES_REQUEST',
    FIND_GAMES_SUCCESS = 'FIND_GAMES_SUCCESS',
    FIND_GAMES_FAIL = 'FIND_GAMES_FAIL',

    GET_GAME_REQUEST = 'GET_GAME_REQUEST',
    GET_GAME_SUCCESS = 'GET_GAME_SUCCESS',
    GET_GAME_FAIL = 'GET_GAME_FAIL',
}
