export enum OrderActionType {
    GET_LIBARY_REQUEST = 'GET_LIBARY_REQUEST',
    GET_LIBARY_SUCCESS = 'GET_LIBARY_SUCCESS',
    GET_LIBARY_FAIL = 'GET_LIBARY_FAIL',

    CHECK_IN_LIBRARY_REQUEST = 'CHECK_IN_LIBRARY_REQUEST',
    CHECK_IN_LIBRARY_SUCCESS = 'CHECK_IN_LIBRARY_SUCCESS',
    CHECK_IN_LIBRARY_FAIL = 'CHECK_IN_LIBRARY_FAIL',

    ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST',
    ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS',
    ORDER_PAY_FAIL = 'ORDER_PAY_FAIL',

    ORDER_PAY_RESET = 'ORDER_PAY_RESET',
}
