export enum WishlistActionType {
    GET_ALL_WISHLIST_REQUEST = 'GET_ALL_WISHLIST_REQUEST',
    GET_ALL_WISHLIST_SUCCESS = 'GET_ALL_WISHLIST_SUCCESS',
    GET_ALL_WISHLIST_FAIL = 'GET_ALL_WISHLIST_FAIL',

    CHECK_IN_WISHLIST_REQUEST = 'CHECK_IN_WISHLIST_REQUEST',
    CHECK_IN_WISHLIST_SUCCESS = 'CHECK_IN_WISHLIST_SUCCESS',
    CHECK_IN_WISHLIST_FAIL = 'CHECK_IN_WISHLIST_FAIL',

    CREATE_WISHLIST_REQUEST = 'CREATE_WISHLIST_REQUEST',
    CREATE_WISHLIST_SUCCESS = 'CREATE_WISHLIST_SUCCESS',
    CREATE_WISHLIST_FAIL = 'CREATE_WISHLIST_FAIL',

    DELETE_WISHLIST_REQUEST = 'DELETE_WISHLIST_REQUEST',
    DELETE_WISHLIST_SUCCESS = 'DELETE_WISHLIST_SUCCESS',
    DELETE_WISHLIST_FAIL = 'DELETE_WISHLIST_FAIL',
}
